import type { ThemeConfig } from '../core/types';

export const aiSecretaryTheme: ThemeConfig = {
  id: 'ai_secretary',
  title: 'AI秘書タイクーン',
  hookText: 'ポンコツAIに100円だけ渡した結果…',
  colors: {
    primary: '#00D4FF',
    secondary: '#7B2FF7',
    accent: '#FFD700',
    background: '#0D0D2B',
    surface: '#1B1B4B',
    text: '#F0F0FF',
  },
  labels: {
    mainAction: '🤖 タスク実行',
    income: '収益/秒',
    coinLabel: '💰 売上',
  },
  producers: [
    {
      id: 'ai_clerk',
      name: '🤖 AI秘書くん',
      baseIncome: 1.0,
      baseCost: 100,
      icon: '🤖',
      description: '基本的なタスクを処理するAI',
    },
    {
      id: 'ai_assistant',
      name: '💼 AIアシスタント',
      baseIncome: 4.5,
      baseCost: 350,
      icon: '💼',
      description: 'メール返信や資料作成を担当',
    },
    {
      id: 'ai_manager',
      name: '🧠 AIマネージャー',
      baseIncome: 14,
      baseCost: 1300,
      icon: '🧠',
      description: 'チームを統括する高機能AI',
    },
    {
      id: 'ai_director',
      name: '👑 AIディレクター',
      baseIncome: 50,
      baseCost: 5000,
      icon: '👑',
      description: '会社全体を最適化するAI',
    },
  ],
  upgrades: [
    {
      id: 'upgrade_ai_lv2',
      name: 'AIスキルLv.2',
      description: '処理速度が2倍に！',
      cost: 500,
      effect: 2,
      targetProducerId: 'ai_clerk',
    },
    {
      id: 'upgrade_assistant_pro',
      name: 'アシスタント強化',
      description: '依頼精度が1.6倍向上',
      cost: 1800,
      effect: 1.6,
      targetProducerId: 'ai_assistant',
    },
    {
      id: 'upgrade_manager_vip',
      name: 'マネージャーVIP',
      description: '戦略立案能力が2.2倍に！',
      cost: 6000,
      effect: 2.2,
      targetProducerId: 'ai_manager',
    },
  ],
  milestones: [
    {
      id: 'office_upgrade',
      condition: { coins: 800 },
      visualState: 'office_desk',
      title: '普通のデスクに昇格！',
      description: '段ボール机からちゃんとしたデスクへ',
    },
    {
      id: 'office_floor',
      condition: { coins: 5000 },
      visualState: 'modern_office',
      title: 'オフィスフロア契約',
      description: '本格的なオフィスビルに移転！',
    },
    {
      id: 'tower',
      condition: { coins: 25000 },
      visualState: 'highrise',
      title: '自社ビル建設！',
      description: '高層ビルが完成！AI帝国の始まり',
    },
  ],
  scenario: [
    { atMs: 0, action: 'addCoins', payload: { amount: 30 } },
    { atMs: 1000, action: 'showPopup', payload: { text: 'AI秘書「タスクを受け付けました！」' } },
    { atMs: 2000, action: 'addCoins', payload: { amount: 80 } },
    { atMs: 3000, action: 'showPopup', payload: { text: '📧 メール返信完了 ×10件' } },
    { atMs: 4000, action: 'addCoins', payload: { amount: 150 } },
    { atMs: 5000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_ai_lv2' } },
    { atMs: 6000, action: 'showPopup', payload: { text: 'AI「スキルアップしました！」' } },
    { atMs: 8000, action: 'addCoins', payload: { amount: 500 } },
    { atMs: 10000, action: 'unlockMilestone', payload: { milestoneId: 'office_upgrade' } },
    { atMs: 12000, action: 'showPopup', payload: { text: '📊 売上レポート：今月の利益 +850円' } },
    { atMs: 14000, action: 'addCoins', payload: { amount: 1000 } },
    { atMs: 16000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_assistant_pro' } },
    { atMs: 18000, action: 'showPopup', payload: { text: '🏢 新AI社員「AIマーケター」を開発中…' } },
    { atMs: 20000, action: 'addCoins', payload: { amount: 3000 } },
    { atMs: 22000, action: 'unlockMilestone', payload: { milestoneId: 'office_floor' } },
    { atMs: 25000, action: 'showPopup', payload: { text: '🔥 月商1000万円突破！さらなる拡大へ！' } },
  ],
};