import type { ThemeConfig } from '../core/types';

export const junkRepairTheme: ThemeConfig = {
  id: 'junk_repair',
  title: 'ジャンク家電リペアタイクーン',
  hookText: '100円のジャンク品を修理して売ってみた',
  colors: {
    primary: '#FF6B35',
    secondary: '#F7C59F',
    accent: '#004E64',
    background: '#1A1A2E',
    surface: '#16213E',
    text: '#E8E8E8',
  },
  labels: {
    mainAction: '🧰 修理する',
    income: '利益/秒',
    coinLabel: '💰 所持金',
  },
  producers: [
    {
      id: 'repair_bench',
      name: '🔧 修理台',
      baseIncome: 1.2,
      baseCost: 100,
      icon: '🔧',
      description: 'ジャンク品を修理する作業台',
    },
    {
      id: 'staff',
      name: '👷 修理スタッフ',
      baseIncome: 4.8,
      baseCost: 350,
      icon: '👷',
      description: '修理を手伝ってくれるスタッフ',
    },
    {
      id: 'tools',
      name: '🔨 専門工具セット',
      baseIncome: 15,
      baseCost: 1200,
      icon: '🔨',
      description: '高級修理工具で効率アップ',
    },
    {
      id: 'showroom',
      name: '🏪 展示販売スペース',
      baseIncome: 45,
      baseCost: 4000,
      icon: '🏪',
      description: '修理品を店内で販売',
    },
  ],
  upgrades: [
    {
      id: 'upgrade_bench',
      name: '修理台Lv.2',
      description: '修理台の効率が2倍に！',
      cost: 500,
      effect: 2,
      targetProducerId: 'repair_bench',
    },
    {
      id: 'upgrade_staff',
      name: '熟練スタッフ研修',
      description: 'スタッフの修理速度が1.5倍',
      cost: 1500,
      effect: 1.5,
      targetProducerId: 'staff',
    },
    {
      id: 'upgrade_tools_pro',
      name: 'プロ用工具セット',
      description: '工具効率が2.5倍に！',
      cost: 5000,
      effect: 2.5,
      targetProducerId: 'tools',
    },
  ],
  milestones: [
    {
      id: 'shop_open',
      condition: { coins: 800 },
      visualState: 'small_shop',
      title: '中古ガジェットショップOPEN',
      description: '小さな店舗を開いた！見た目が変化',
    },
    {
      id: 'warehouse',
      condition: { coins: 5000 },
      visualState: 'warehouse',
      title: '倉庫拡張完了',
      description: '倉庫が広くなり、在庫管理が効率的に！',
    },
    {
      id: 'flagship_store',
      condition: { coins: 20000 },
      visualState: 'flagship',
      title: '旗艦店オープン！',
      description: '大都市に旗艦店を構えた！',
    },
  ],
  scenario: [
    { atMs: 0, action: 'addCoins', payload: { amount: 50 } },
    { atMs: 1000, action: 'addCoins', payload: { amount: 100 } },
    { atMs: 2000, action: 'addCoins', payload: { amount: 150 } },
    { atMs: 3000, action: 'showPopup', payload: { text: '100円のジャンク品を仕入れました！' } },
    { atMs: 4000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_bench' } },
    { atMs: 5000, action: 'addCoins', payload: { amount: 500 } },
    { atMs: 6000, action: 'showPopup', payload: { text: '修理完了！販売価格 980円！' } },
    { atMs: 7000, action: 'addCoins', payload: { amount: 980 } },
    { atMs: 8000, action: 'showPopup', payload: { text: '📈 利益 +850円！' } },
    { atMs: 10000, action: 'unlockMilestone', payload: { milestoneId: 'shop_open' } },
    { atMs: 12000, action: 'addCoins', payload: { amount: 2000 } },
    { atMs: 15000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_staff' } },
    { atMs: 18000, action: 'showPopup', payload: { text: '⭐ レア商品「プレステ6」を発見！' } },
    { atMs: 20000, action: 'addCoins', payload: { amount: 5000 } },
    { atMs: 22000, action: 'unlockMilestone', payload: { milestoneId: 'warehouse' } },
    { atMs: 25000, action: 'showPopup', payload: { text: '🔥 月商100万円突破！次の目標は旗艦店！' } },
  ],
};