import type { ThemeConfig } from '../core/types';

export const petRoomTheme: ThemeConfig = {
  id: 'pet_room',
  title: 'ペット部屋づくり',
  hookText: '寝てる間にペットが部屋を改造してた',
  colors: {
    primary: '#FF89D5',
    secondary: '#A8E6CF',
    accent: '#FFD93D',
    background: '#2D1B4E',
    surface: '#3D2B5E',
    text: '#FFF5F5',
  },
  labels: {
    mainAction: '🐾 なでる',
    income: '快適度/秒',
    coinLabel: '🧸 コイン',
  },
  producers: [
    {
      id: 'hamster',
      name: '🐹 ハムスター',
      baseIncome: 1.1,
      baseCost: 80,
      icon: '🐹',
      description: 'せっせとコインを集める小さな働き者',
    },
    {
      id: 'cat',
      name: '🐱 ねこ',
      baseIncome: 4.2,
      baseCost: 300,
      icon: '🐱',
      description: '優雅に部屋を飾ってくれる',
    },
    {
      id: 'dog',
      name: '🐶 わんこ',
      baseIncome: 13,
      baseCost: 1100,
      icon: '🐶',
      description: '大きな家具を運んでくる',
    },
    {
      id: 'rabbit',
      name: '🐰 うさぎ',
      baseIncome: 42,
      baseCost: 3800,
      icon: '🐰',
      description: '魔法のように部屋を華やかに',
    },
  ],
  upgrades: [
    {
      id: 'upgrade_food',
      name: '🍖 ごちそうセット',
      description: 'ペットのやる気が1.8倍に！',
      cost: 400,
      effect: 1.8,
      targetProducerId: 'hamster',
    },
    {
      id: 'upgrade_toy',
      name: '🧶 おもちゃコレクション',
      description: 'ねこの遊び時間が増えて効率1.5倍',
      cost: 1400,
      effect: 1.5,
      targetProducerId: 'cat',
    },
    {
      id: 'upgrade_park',
      name: '🌳 ドッグラン拡張',
      description: 'わんこの運動量アップで効率2.3倍',
      cost: 4500,
      effect: 2.3,
      targetProducerId: 'dog',
    },
  ],
  milestones: [
    {
      id: 'cozy_room',
      condition: { coins: 600 },
      visualState: 'cozy',
      title: '🌸 かわいい部屋になった！',
      description: '空っぽの部屋に家具が揃い始めた',
    },
    {
      id: 'pet_paradise',
      condition: { coins: 4000 },
      visualState: 'paradise',
      title: '🐾 ペットパラダイス！',
      description: '部屋中がペットの遊び場に！',
    },
    {
      id: 'pet_mansion',
      condition: { coins: 18000 },
      visualState: 'mansion',
      title: '🏰 ペットのお城完成！',
      description: 'もう立派なお屋敷！ペットも大満足',
    },
  ],
  scenario: [
    { atMs: 0, action: 'addCoins', payload: { amount: 40 } },
    { atMs: 1000, action: 'showPopup', payload: { text: '🐹 ハムスターがコインを集めてる…' } },
    { atMs: 2000, action: 'addCoins', payload: { amount: 80 } },
    { atMs: 3000, action: 'showPopup', payload: { text: '🐱 ねこが新しいクッションを持ってきた！' } },
    { atMs: 4000, action: 'addCoins', payload: { amount: 120 } },
    { atMs: 5000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_food' } },
    { atMs: 6000, action: 'showPopup', payload: { text: '🐶 わんこ「わん！もっと遊びたい！」' } },
    { atMs: 8000, action: 'addCoins', payload: { amount: 300 } },
    { atMs: 10000, action: 'unlockMilestone', payload: { milestoneId: 'cozy_room' } },
    { atMs: 12000, action: 'showPopup', payload: { text: '🧸 新しい家具「ふわふわカーペット」' } },
    { atMs: 14000, action: 'addCoins', payload: { amount: 800 } },
    { atMs: 16000, action: 'buyUpgrade', payload: { upgradeId: 'upgrade_toy' } },
    { atMs: 18000, action: 'showPopup', payload: { text: '⭐ レアペット「フェネック」が遊びに来た！' } },
    { atMs: 20000, action: 'addCoins', payload: { amount: 2000 } },
    { atMs: 22000, action: 'unlockMilestone', payload: { milestoneId: 'pet_paradise' } },
    { atMs: 25000, action: 'showPopup', payload: { text: '💖 ペットの満足度MAX！お城を建てよう！' } },
  ],
};